services:
  # PostgreSQL app DB
  postgres:
    image: postgres:14.19-alpine3.21
    container_name: aston-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - aston-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 6

  # Kafka
  kafka:
    image: apache/kafka:4.1.1
    container_name: aston-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      # --------- LISTENERS ----------
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      # --------- CONTROLLER ----------
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # --------- PROTOCOL ----------
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # --------- allow LISTENER ----------
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=3
    networks:
      - aston-network

  # aston-hibernate app
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: aston-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8080:8080"  # localhost:8080
    depends_on:
      - postgres
      - kong
      - kafka
    networks:
      - aston-network
    volumes:
      - ./logs:/app/logs

  # Kong DB
  kong-database:
    image: postgres:14.19-alpine3.21
    container_name: kong-database
    environment:
      POSTGRES_USER: ${KONG_PG_USER}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD}
      POSTGRES_DB: ${KONG_DATABASE}
    volumes:
      - kong-database-data:/var/lib/postgresql/data
    networks:
      - aston-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${KONG_PG_USER}" , "-d" , "${KONG_DATABASE}"]
      interval: 5s
      timeout: 10s
      retries: 6

 # Kong Migrations (one-time job)
  kong-migration:
    image: kong:3.9
    container_name: kong-migration
    depends_on:
      kong-database:
        condition: service_healthy
    command: ["kong", "migrations", "bootstrap"]
    environment:
      KONG_PG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_MIGRATE: true
    networks:
      - aston-network
    restart: "no"  # no restart after use

  # Kong Gateway
  kong:
    image: kong:3.9
    container_name: kong-gateway
    environment:
      KONG_PG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD}
      KONG_PROXY_ACCESS_LOG: ${KONG_PROXY_ACCESS_LOG}
      KONG_ADMIN_ACCESS_LOG: ${KONG_ADMIN_ACCESS_LOG}
      KONG_PROXY_ERROR_LOG: ${KONG_PROXY_ERROR_LOG}
      KONG_ADMIN_ERROR_LOG: ${KONG_ADMIN_ERROR_LOG}
      KONG_ADMIN_LISTEN: ${KONG_ADMIN_LISTEN}
      KONG_PROXY_LISTEN: ${KONG_PROXY_LISTEN}
    ports:
      - "8000:8000"   # Proxy (HTTP)
      - "8443:8443"   # Proxy (HTTPS)
      - "8001:8001"   # Admin API
      - "8444:8444"   # Admin API (HTTPS)
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_completed_successfully
    networks:
      - aston-network
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 60s
      retries: 10
      start_period: 60s
    restart: always

networks:
  aston-network:
    driver: bridge

volumes:
  postgres-data:
  kong-database-data:
