services:
  postgres:
    image: postgres:14.19-alpine3.21
    container_name: aston-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - aston-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 6

  kafka:
    image: apache/kafka:4.1.1
    container_name: aston-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # --------- LISTENERS ----------
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://aston-kafka:9092
      # --------- CONTROLLER ----------
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # --------- PROTOCOL ----------
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # --------- allow LISTENER ----------
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - aston-network
    healthcheck:
      test: ["CMD", "bash", "-c", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 10s          # checking interval
      timeout: 5s            # waiting until checking complete
      retries: 5             # count missing to «unhealthy»
      start_period: 30s      # boot‑time

  eureka-server:
    image: aston-hibernate-eureka-server:lates
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - 8761:8761
    networks:
      - aston-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  spring-gateway:
    image: aston-hibernate-spring-gateway:lates
    build:
      context: ./spring-gateway
      dockerfile: Dockerfile
    container_name: spring-gateway
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://configuration-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    ports:
      - 8000:8000
    depends_on:
      eureka-server:
        condition: service_healthy
      configuration-server:
        condition: service_healthy
    networks:
      - aston-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Services
  user-service:
    build:
      context: ./core-app
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: aston-kafka:9092
      SPRING_CONFIG_IMPORT: optional:configserver:http://configuration-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    ports:
      - 8080:8080
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    networks:
      - aston-network
    volumes:
      - ./logs:/app/logs

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service  
    environment:
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: aston-kafka:9092
      SPRING_CONFIG_IMPORT: optional:configserver:http://configuration-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    ports:
      - 8082:8082
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      configuration-server:
        condition: service_healthy
    networks:
      - aston-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  configuration-server:
    build:
      context: ./configuration-server
      dockerfile: Dockerfile
    container_name: configuration-server
    ports:
      - 8888:8888
    networks:
      - aston-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  aston-network:
    driver: bridge

volumes:
  postgres-data:
  kong-database-data:
