spring:
  application:
    name: aston-hibernate

  datasource:
    url: jdbc:postgresql://localhost:5432/intensive_2
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true              
    properties:
      hibernate.format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

  mail:
    host: smtp.mail.ru
    port: 465
    username: ${SMTP_USERNAME}  # переменная среды
    password: ${SMTP_PASSWORD}  # переменная среды
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true  # обязательное требование Mail.ru
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465

email:
  sender:
    default: ${SMTP_USERNAME}  # отправитель = логин SMTP

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
      registerWithEureka: true     # Регистрироваться в Eureka
      fetchRegistry: true         # Загружать реестр сервисов
    instance:
      preferIpAddress: false     # Использовать имя хоста (не IP)

logging:
  file:
    #path: ./logs/
    name: ./logs/aston-hibernate.log
  level:
    # org.apache.kafka: DEBUG
    # org.springframework.kafka: DEBUG
    ru.redcarpet: INFO

